apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-learning
  template:
    metadata:
      labels:
        app: devops-learning
    spec:
      containers:
        - name: devops-learning-server
          image: ghcr.io/machdees/devops_learning
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP